version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: 'pdca-ccontainer'
    restart: always
    build: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo
    depends_on:
      - "mongo"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000"]
        interval: 5s
        timeout: 10s
        retries: 999